# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale:  "en-US"
title: BirdSongs
name: BirdSongs
#title_separator: "-"
subtitle: "A python package to analyze, visualize and generate synthetic birdsongs."
description: "A python package to analyze, visualize and generate synthetic birdsongs."
email: saguileran@unal.edu.co
#version: 0.1
#description: >- # this means to ignore newlines until "baseurl:"
#  Thesis documentation and codes
#baseurl: "" # the subpath of your site, e.g. /blog
url: https://saguileran.github.io/birdsongs/ # the base hostname & protocol for your site, e.g. http://example.com
repository: https://github.com/saguileran/birdsongs
logo: /assets/images/logo.png
#twitter_username: saguileran
#github_username:  saguileran

# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-readme-index

# Site Author
author:
  name             : "Sebastian Aguilera Novoa"
  avatar           : "/assets/images/photo.png"
  bio              : "Hi, I'm physicist interested on computer science."
  location         : "Bogotá, CO"
  email            : "saguileran@unal.edu.co"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:saguileran@unal.edu.co
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://saguileran.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/saguileran"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/saguileran"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saguileran"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/saguileran"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

defaults:
- scope:
    path: ""
    type: docs
  values:
    layout: docs

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
